name: CI Pipeline

on:
  push:
    branches:
      - main  # Change to 'master' if that's your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pip install -r requirement.txt

      - name: Run Tests
        run: |
          pytest
